#!/bin/sh

#
#  Copyright (C) 2004-2006 Intel Corporation
#  
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#  
#
# The source code contained or described herein and all documents related to the source code
# ("Material") are owned by Intel Corporation or its suppliers or licensors. Title to the
# Material remains with Intel Corporation or its suppliers and licensors. The Material may
# contain trade secrets and proprietary and confidential information of Intel Corporation and
# its suppliers and licensors, and is protected by worldwide copyright and trade secret laws
# and treaty provisions. No part of the Material may be used, copied, reproduced, modified,
# published, uploaded, posted, transmitted, distributed, or disclosed in any way without
# Intels prior express written permission.
#
#

echo /usr/intel/pkgs/gcc/2.95.3/bin/gcc $*
/usr/intel/pkgs/gcc/2.95.3/bin/gcc $*
