/*
 * Copyright (C) 2001-2006 Intel Corporation
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * 
 */

/* Structures for describing each opcode */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "icode.h"
#include "opcodes.h"
#include "newinst.h"

#ifdef NEW_MVI
#define OP04FORMAT Float
#else
#define OPO4FORMAT Reserved
#endif

/* The instruction formats corresponding to the opcodes of instructions */
Iformat OpFormat[] = {
   PAL, Reserved, Reserved, Reserved, OP04FORMAT, Reserved, Reserved, Reserved,
   Memory, Memory, Memory, Memory, Memory, Memory, Memory, Memory,
   Operate, Operate, Operate, Operate, Float, Float, Float, Float,
   Memory, PAL, Branch, Memory, Operate, PAL, PAL, PAL,
   Memory, Memory, Memory, Memory, Memory, Memory, Memory, Memory,
   Memory, Memory, Memory, Memory, Memory, Memory, Memory, Memory,
   Branch, Branch, Branch, Branch, Branch, Branch, Branch, Branch,
   Branch, Branch, Branch, Branch, Branch, Branch, Branch, Branch
  };

	
group_t pal_group[] = {
  {PAL_gentrap,	pal_gentrap},
  {PAL_rduniq,	pal_rduniq},
  {PAL_wruniq,	pal_wruniq},
  {PAL_bpt,	pal_bpt},
  {PAL_bugchk,	pal_bugchk},
  {PAL_chmk,	pal_chmk},
  {PAL_callsys,	pal_callsys},
  {PAL_imb,	pal_imb},
  {PAL_halt,	pal_halt},
  {PAL_draina,	pal_draina},
  {PAL_nphalt,	pal_nphalt},
  {PAL_cobratt,	pal_cobratt},
  {PAL_cserve ,	pal_cserve },
  {PAL_ipir,	pal_ipir},
  {PAL_cflush,	pal_cflush},
  {PAL_rti,	pal_rti},
  {PAL_rtsys,	pal_rtsys},
  {PAL_whami,	pal_whami},
  {PAL_rdusp,	pal_rdusp},
  {PAL_wrperfmon,	pal_wrperfmon},
  {PAL_wrusp,	pal_wrusp},
  {PAL_wrkgp,	pal_wrkgp},
  {PAL_rdps,	pal_rdps},
  {PAL_swpipl,	pal_swpipl},
  {PAL_wrent,	pal_wrent},
  {PAL_tbi,	pal_tbi},
  {PAL_rdval,	pal_rdval},
  {PAL_wrval,	pal_wrval},
  {PAL_swpctx,	pal_swpctx},
  {PAL_jtopal,	pal_jtopal},
  {PAL_wrvptptr,	pal_wrvptptr},
  {PAL_wrfen,	pal_wrfen},
  {PAL_mtpr_mces,	pal_mtpr_mces},
  {0, 0}
};

group_t inta_group[] = {
  { inta_addl,	addl_opn },
  { inta_s4addl,	s4addl_opn },
  { inta_subl,	subl_opn },
  { inta_s4subl,	s4subl_opn },
#ifdef NEW_MVI
  { inta_cmpwge,	cmpwge_opn },
#endif
  { inta_cmpbge,	cmpbge_opn },
  { inta_s8addl,	s8addl_opn },
  { inta_s8subl,	s8subl_opn },
  { inta_cmpult,	cmpult_opn },
  { inta_addq,	addq_opn },
  { inta_s4addq,	s4addq_opn },
  { inta_subq,	subq_opn },
  { inta_s4subq,	s4subq_opn },
  { inta_cmpeq,	cmpeq_opn },
  { inta_s8addq,	s8addq_opn },
  { inta_s8subq,	s8subq_opn },
  { inta_cmpule,	cmpule_opn },
  { inta_addlv,	addlv_opn },
  { inta_sublv,	sublv_opn },
  { inta_cmplt,	cmplt_opn },
  { inta_addqv,	addqv_opn },
  { inta_subqv,	subqv_opn },
  { inta_cmple,	cmple_opn },
  {0, 0}
};

group_t intl_group[] = {
  { intl_and,	and_opn },
  { intl_bic,	bic_opn },
  { intl_cmovlbs,	cmovlbs_opn },
  { intl_cmovlbc,	cmovlbc_opn },
  { intl_bis,	bis_opn },
  { intl_cmoveq,	cmoveq_opn },
  { intl_cmovne,	cmovne_opn },
  { intl_ornot,	ornot_opn },
  { intl_xor,	xor_opn },
  { intl_cmovlt,	cmovlt_opn },
  { intl_cmovge,	cmovge_opn },
  { intl_eqv,	eqv_opn },
  { intl_amask,	amask_opn },
  { intl_cmovle,	cmovle_opn },
  { intl_cmovgt,	cmovgt_opn },
  { intl_implver,	implver_opn },
  {0, 0}
};

group_t ints_group[] = {
  {ints_mskbl,	mskbl_opn},
  {ints_extbl,	extbl_opn},
  {ints_insbl,	insbl_opn},
  {ints_mskwl,	mskwl_opn},
  {ints_extwl,	extwl_opn},
  {ints_inswl,	inswl_opn},
  {ints_mskll,	mskll_opn},
  {ints_extll,	extll_opn},
  {ints_insll,	insll_opn},
  {ints_zap,	zap_opn},
  {ints_zapnot,	zapnot_opn},
  {ints_mskql,	mskql_opn},
  {ints_srl,	srl_opn},
  {ints_extql,	extql_opn},
  {ints_sll,	sll_opn},
  {ints_insql,	insql_opn},
  {ints_sra,	sra_opn},
  {ints_mskwh,	mskwh_opn},
  {ints_inswh,	inswh_opn},
  {ints_extwh,	extwh_opn},
  {ints_msklh,	msklh_opn},
  {ints_inslh,	inslh_opn},
  {ints_extlh,	extlh_opn},
  {ints_mskqh,	mskqh_opn},
  {ints_insqh,	insqh_opn},
  {ints_extqh,	extqh_opn},
  {0, 0}
};

group_t fltv_group[] = {
  {fltv_addfc,	addfc_opn},
  {fltv_subfc,	subfc_opn},
  {fltv_mulfc,	mulfc_opn},
  {fltv_divfc,	divfc_opn},
  {fltv_cvtdgc,	cvtdgc_opn},
  {fltv_addgc,	addgc_opn},
  {fltv_subgc,	subgc_opn},
  {fltv_mulgc,	mulgc_opn},
  {fltv_divgc,	divgc_opn},
  {fltv_cvtgfc,	cvtgfc_opn},
  {fltv_cvtgdc,	cvtgdc_opn},
  {fltv_cvtgqc,	cvtgqc_opn},
  {fltv_cvtqfc,	cvtqfc_opn},
  {fltv_cvtqgc,	cvtqgc_opn},
  {fltv_addf,	addf_opn},
  {fltv_subf,	subf_opn},
  {fltv_mulf,	mulf_opn},
  {fltv_divf,	divf_opn},
  {fltv_cvtdg,	cvtdg_opn},
  {fltv_addg,	addg_opn},
  {fltv_subg,	subg_opn},
  {fltv_mulg,	mulg_opn},
  {fltv_divg,	divg_opn},
  {fltv_cmpgeq,	cmpgeq_opn},
  {fltv_cmpglt,	cmpglt_opn},
  {fltv_cmpgle,	cmpgle_opn},
  {fltv_cvtgf,	cvtgf_opn},
  {fltv_cvtgd,	cvtgd_opn},
  {fltv_cvtgq,	cvtgq_opn},
  {fltv_cvtqf,	cvtqf_opn},
  {fltv_cvtqg,	cvtqg_opn},
  {fltv_addfuc,	addfuc_opn},
  {fltv_subfuc,	subfuc_opn},
  {fltv_mulfuc,	mulfuc_opn},
  {fltv_divfuc,	divfuc_opn},
  {fltv_cvtdguc,	cvtdguc_opn},
  {fltv_addguc,	addguc_opn},
  {fltv_subguc,	subguc_opn},
  {fltv_mulguc,	mulguc_opn},
  {fltv_divguc,	divguc_opn},
  {fltv_cvtgfuc,	cvtgfuc_opn},
  {fltv_cvtgduc,	cvtgduc_opn},
  {fltv_cvtgqvc,	cvtgqvc_opn},
  {fltv_addfu,	addfu_opn},
  {fltv_subfu,	subfu_opn},
  {fltv_mulfu,	mulfu_opn},
  {fltv_divfu,	divfu_opn},
  {fltv_cvtdgu,	cvtdgu_opn},
  {fltv_addgu,	addgu_opn},
  {fltv_subgu,	subgu_opn},
  {fltv_mulgu,	mulgu_opn},
  {fltv_divgu,	divgu_opn},
  {fltv_cvtgfu,	cvtgfu_opn},
  {fltv_cvtgdu,	cvtgdu_opn},
  {fltv_cvtgqv,	cvtgqv_opn},
  {fltv_addfsc,	addfsc_opn},
  {fltv_subfsc,	subfsc_opn},
  {fltv_mulfsc,	mulfsc_opn},
  {fltv_divfsc,	divfsc_opn},
  {fltv_cvtdgsc,	cvtdgsc_opn},
  {fltv_addgsc,	addgsc_opn},
  {fltv_subgsc,	subgsc_opn},
  {fltv_mulgsc,	mulgsc_opn},
  {fltv_divgsc,	divgsc_opn},
  {fltv_cvtgfsc,	cvtgfsc_opn},
  {fltv_cvtgdsc,	cvtgdsc_opn},
  {fltv_cvtgqsc,	cvtgqsc_opn},
  {fltv_addfs,	addfs_opn},
  {fltv_subfs,	subfs_opn},
  {fltv_mulfs,	mulfs_opn},
  {fltv_divfs,	divfs_opn},
  {fltv_cvtdgs,	cvtdgs_opn},
  {fltv_addgs,	addgs_opn},
  {fltv_subgs,	subgs_opn},
  {fltv_mulgs,	mulgs_opn},
  {fltv_divgs,	divgs_opn},
  {fltv_cmpgeqs,	cmpgeqs_opn},
  {fltv_cmpglts,	cmpglts_opn},
  {fltv_cmpgles,	cmpgles_opn},
  {fltv_cvtgfs,	cvtgfs_opn},
  {fltv_cvtgds,	cvtgds_opn},
  {fltv_cvtgqs,	cvtgqs_opn},
  {fltv_addfsuc,	addfsuc_opn},
  {fltv_subfsuc,	subfsuc_opn},
  {fltv_mulfsuc,	mulfsuc_opn},
  {fltv_divfsuc,	divfsuc_opn},
  {fltv_cvtdgsuc,	cvtdgsuc_opn},
  {fltv_addgsuc,	addgsuc_opn},
  {fltv_subgsuc,	subgsuc_opn},
  {fltv_mulgsuc,	mulgsuc_opn},
  {fltv_divgsuc,	divgsuc_opn},
  {fltv_cvtgfsuc,	cvtgfsuc_opn},
  {fltv_cvtgdsuc,	cvtgdsuc_opn},
  {fltv_cvtgqsvc,	cvtgqsvc_opn},
  {fltv_addfsu,	addfsu_opn},
  {fltv_subfsu,	subfsu_opn},
  {fltv_mulfsu,	mulfsu_opn},
  {fltv_divfsu,	divfsu_opn},
  {fltv_cvtdgsu,	cvtdgsu_opn},
  {fltv_addgsu,	addgsu_opn},
  {fltv_subgsu,	subgsu_opn},
  {fltv_mulgsu,	mulgsu_opn},
  {fltv_divgsu,	divgsu_opn},
  {fltv_cvtgfsu,	cvtgfsu_opn},
  {fltv_cvtgdsu,	cvtgdsu_opn},
  {fltv_cvtgqsv,	cvtgqsv_opn},
  {0, 0}
};

group_t flti_group[] = {
  {flti_addsc,	addsc_opn},
  {flti_subsc,	subsc_opn},
  {flti_mulsc,	mulsc_opn},
  {flti_divsc,	divsc_opn},
  {flti_addtc,	addtc_opn},
  {flti_subtc,	subtc_opn},
  {flti_multc,	multc_opn},
  {flti_divtc,	divtc_opn},
  {flti_cvttsc,	cvttsc_opn},
  {flti_cvttqc,	cvttqc_opn},
  {flti_cvtqsc,	cvtqsc_opn},
  {flti_cvtqtc,	cvtqtc_opn},
  {flti_addsm,	addsm_opn},
  {flti_subsm,	subsm_opn},
  {flti_mulsm,	mulsm_opn},
  {flti_divsm,	divsm_opn},
  {flti_addtm,	addtm_opn},
  {flti_subtm,	subtm_opn},
  {flti_multm,	multm_opn},
  {flti_divtm,	divtm_opn},
  {flti_cvttsm,	cvttsm_opn},
  {flti_cvttqm,	cvttqm_opn},
  {flti_cvtqsm,	cvtqsm_opn},
  {flti_cvtqtm,	cvtqtm_opn},
  {flti_adds,	adds_opn},
  {flti_subs,	subs_opn},
  {flti_muls,	muls_opn},
  {flti_divs,	divs_opn},
  {flti_addt,	addt_opn},
  {flti_subt,	subt_opn},
  {flti_mult,	mult_opn},
  {flti_divt,	divt_opn},
  {flti_cmptun,	cmptun_opn},
  {flti_cmpteq,	cmpteq_opn},
  {flti_cmptlt,	cmptlt_opn},
  {flti_cmptle,	cmptle_opn},
  {flti_cvtts,	cvtts_opn},
  {flti_cvttq,	cvttq_opn},
  {flti_cvtqs,	cvtqs_opn},
  {flti_cvtqt,	cvtqt_opn},
  {flti_addsd,	addsd_opn},
  {flti_subsd,	subsd_opn},
  {flti_mulsd,	mulsd_opn},
  {flti_divsd,	divsd_opn},
  {flti_addtd,	addtd_opn},
  {flti_subtd,	subtd_opn},
  {flti_multd,	multd_opn},
  {flti_divtd,	divtd_opn},
  {flti_cvttsd,	cvttsd_opn},
  {flti_cvttqd,	cvttqd_opn},
  {flti_cvtqsd,	cvtqsd_opn},
  {flti_cvtqtd,	cvtqtd_opn},
  {flti_addsuc,	addsuc_opn},
  {flti_subsuc,	subsuc_opn},
  {flti_mulsuc,	mulsuc_opn},
  {flti_divsuc,	divsuc_opn},
  {flti_addtuc,	addtuc_opn},
  {flti_subtuc,	subtuc_opn},
  {flti_multuc,	multuc_opn},
  {flti_divtuc,	divtuc_opn},
  {flti_cvttsuc,	cvttsuc_opn},
  {flti_cvttqvc,	cvttqvc_opn},
  {flti_addsum,	addsum_opn},
  {flti_subsum,	subsum_opn},
  {flti_mulsum,	mulsum_opn},
  {flti_divsum,	divsum_opn},
  {flti_addtum,	addtum_opn},
  {flti_subtum,	subtum_opn},
  {flti_multum,	multum_opn},
  {flti_divtum,	divtum_opn},
  {flti_cvttsum,	cvttsum_opn},
  {flti_cvttqvm,	cvttqvm_opn},
  {flti_addsu,	addsu_opn},
  {flti_subsu,	subsu_opn},
  {flti_mulsu,	mulsu_opn},
  {flti_divsu,	divsu_opn},
  {flti_addtu,	addtu_opn},
  {flti_subtu,	subtu_opn},
  {flti_multu,	multu_opn},
  {flti_divtu,	divtu_opn},
  {flti_cvttsu,	cvttsu_opn},
  {flti_cvttqv,	cvttqv_opn},
  {flti_addsud,	addsud_opn},
  {flti_subsud,	subsud_opn},
  {flti_mulsud,	mulsud_opn},
  {flti_divsud,	divsud_opn},
  {flti_addtud,	addtud_opn},
  {flti_subtud,	subtud_opn},
  {flti_multud,	multud_opn},
  {flti_divtud,	divtud_opn},
  {flti_cvttsud,	cvttsud_opn},
  {flti_cvttqvd,	cvttqvd_opn},
  {flti_cvtst,		cvtst_opn},
  {flti_cvtsts,		cvtsts_opn},
  {flti_addssuc,	addssuc_opn},
  {flti_subssuc,	subssuc_opn},
  {flti_mulssuc,	mulssuc_opn},
  {flti_divssuc,	divssuc_opn},
  {flti_addtsuc,	addtsuc_opn},
  {flti_subtsuc,	subtsuc_opn},
  {flti_multsuc,	multsuc_opn},
  {flti_divtsuc,	divtsuc_opn},
  {flti_cvttssuc,	cvttssuc_opn},
  {flti_cvttqsvc,	cvttqsvc_opn},
  {flti_addssum,	addssum_opn},
  {flti_subssum,	subssum_opn},
  {flti_mulssum,	mulssum_opn},
  {flti_divssum,	divssum_opn},
  {flti_addtsum,	addtsum_opn},
  {flti_subtsum,	subtsum_opn},
  {flti_multsum,	multsum_opn},
  {flti_divtsum,	divtsum_opn},
  {flti_cvttssum,	cvttssum_opn},
  {flti_cvttqsvm,	cvttqsvm_opn},
  {flti_addssu,		addssu_opn},
  {flti_subssu,		subssu_opn},
  {flti_mulssu,		mulssu_opn},
  {flti_divssu,		divssu_opn},
  {flti_addtsu,		addtsu_opn},
  {flti_subtsu,		subtsu_opn},
  {flti_multsu,		multsu_opn},
  {flti_divtsu,		divtsu_opn},
  {flti_cmptunsu,	cmptunsu_opn},
  {flti_cmpteqsu,	cmpteqsu_opn},
  {flti_cmptltsu,	cmptltsu_opn},
  {flti_cmptlesu,	cmptlesu_opn},
  {flti_cvttssu,	cvttssu_opn},
  {flti_cvttqsv,	cvttqsv_opn},
  {flti_addssud,	addssud_opn},
  {flti_subssud,	subssud_opn},
  {flti_mulssud,	mulssud_opn},
  {flti_divssud,	divssud_opn},
  {flti_addtsud,	addtsud_opn},
  {flti_subtsud,	subtsud_opn},
  {flti_multsud,	multsud_opn},
  {flti_divtsud,	divtsud_opn},
  {flti_cvttssud,	cvttssud_opn},
  {flti_cvttqsvd,	cvttqsvd_opn},
  /*   {flti_cvttss,	cvttss_opn}, */
  {flti_addssuic,	addssuic_opn},
  {flti_subssuic,	subssuic_opn},
  {flti_mulssuic,	mulssuic_opn},
  {flti_divssuic,	divssuic_opn},
  {flti_addtsuic,	addtsuic_opn},
  {flti_subtsuic,	subtsuic_opn},
  {flti_multsuic,	multsuic_opn},
  {flti_divtsuic,	divtsuic_opn},
  {flti_cvttssuic,	cvttssuic_opn},
  {flti_cvttqsvic,	cvttqsvic_opn},
  {flti_cvtqssuic,	cvtqssuic_opn},
  {flti_cvtqtsuic,	cvtqtsuic_opn},
  {flti_addssuim,	addssuim_opn},
  {flti_subssuim,	subssuim_opn},
  {flti_mulssuim,	mulssuim_opn},
  {flti_divssuim,	divssuim_opn},
  {flti_addtsuim,	addtsuim_opn},
  {flti_subtsuim,	subtsuim_opn},
  {flti_multsuim,	multsuim_opn},
  {flti_divtsuim,	divtsuim_opn},
  {flti_cvttssuim,	cvttssuim_opn},
  {flti_cvttqsvim,	cvttqsvim_opn},
  {flti_cvtqssuim,	cvtqssuim_opn},
  {flti_cvtqtsuim,	cvtqtsuim_opn},
  {flti_addssui,	addssui_opn},
  {flti_subssui,	subssui_opn},
  {flti_mulssui,	mulssui_opn},
  {flti_divssui,	divssui_opn},
  {flti_addtsui,	addtsui_opn},
  {flti_subtsui,	subtsui_opn},
  {flti_multsui,	multsui_opn},
  {flti_divtsui,	divtsui_opn},
  {flti_cvttssui,	cvttssui_opn},
  {flti_cvttqsvi,	cvttqsvi_opn},
  {flti_cvtqssui,	cvtqssui_opn},
  {flti_cvtqtsui,	cvtqtsui_opn},
  {flti_addssuid,	addssuid_opn},
  {flti_subssuid,	subssuid_opn},
  {flti_mulssuid,	mulssuid_opn},
  {flti_divssuid,	divssuid_opn},
  {flti_addtsuid,	addtsuid_opn},
  {flti_subtsuid,	subtsuid_opn},
  {flti_multsuid,	multsuid_opn},
  {flti_divtsuid,	divtsuid_opn},
  {flti_cvttssuid,	cvttssuid_opn},
  {flti_cvttqsvid,	cvttqsvid_opn},
  {flti_cvtqssuid,	cvtqssuid_opn},
  {flti_cvtqtsuid,	cvtqtsuid_opn},
  {0, 0}
};

group_t fltl_group[] = {
  {fltl_cvtlq,	cvtlq_opn},
  {fltl_cpys,	cpys_opn},
  {fltl_cpysn,	cpysn_opn},
  {fltl_cpyse,	cpyse_opn},
  {fltl_mt_fpcr,	mt_fpcr_opn},
  {fltl_mf_fpcr,	mf_fpcr_opn},
  {fltl_fcmoveq,	fcmoveq_opn},
  {fltl_fcmovne,	fcmovne_opn},
  {fltl_fcmovlt,	fcmovlt_opn},
  {fltl_fcmovge,	fcmovge_opn},
  {fltl_fcmovle,	fcmovle_opn},
  {fltl_fcmovgt,	fcmovgt_opn},
  {fltl_cvtql,	cvtql_opn},
  {fltl_cvtqlv,	cvtqlv_opn},
  {fltl_cvtqlsv,	cvtqlsv_opn},
  {0, 0}
};

group_t misc_group[] = {
  {misc_trapb,	trapb_opn},
  {misc_excb,	excb_opn},
  {misc_mb,	mb_opn},
  {misc_wmb,	wmb_opn},
  {misc_fetch,	fetch_opn},
  {misc_fetch_m,	fetch_m_opn},
  {misc_rpcc,	rpcc_opn},
  {misc_rc,	rc_opn},
  {misc_rs,	rs_opn},
  {misc_ecb,    ecb_opn},
  {misc_wh64,   wh64_opn},
  {misc_wh64en, wh64en_opn},
  {0, 0}
};

group_t jsr_group[] = {
  {jsr_jmp,    jmp_opn},
  {jsr_jsr,    jsr_opn},
  {jsr_ret,    ret_opn},
  {jsr_jsr_coroutine, jsr_coroutine_opn},
  {0, 0}
};

group_t intm_group[] = {
  {intm_mull,	mull_opn},
  {intm_mulq,	mulq_opn},
  {intm_umulh,	umulh_opn},
  {intm_mullv,	mullv_opn},
  {intm_mulqv,	mulqv_opn},
  {0, 0}
};

#ifdef NEW_MVI
group_t opc04_group[] = {
  {opc04_padd, padd_opn},
  {opc04_psub, psub_opn},
  {opc04_paddc, paddc_opn},  
  {opc04_psubc, psubc_opn},
  {opc04_phadd, phadd_opn},
  {opc04_phsub, phsub_opn},
  {opc04_phsub, phsubr_opn},

  {opc04_pmul, pmul_opn},
  {opc04_pmull, pmull_opn},
  {opc04_pmulls, pmulls_opn},
  {opc04_pmulh, pmulh_opn},
  {opc04_pmulhs, pmulhs_opn},

  {opc04_parcpl, parcpl_opn},
  {opc04_parcplh, parcplh_opn},
  {opc04_parcpll, parcpll_opn},

  {opc04_parsqrt, parsqrt_opn},
  {opc04_parsqrth, parsqrth_opn},
  {opc04_parsqrtl, parsqrtl_opn},

  {opc04_pmovll, pmovll_opn},
  {opc04_pmovlh, pmovlh_opn},
  {opc04_pmovhl, pmovhl_opn},
  {opc04_pmovhh, pmovhh_opn},

  {opc04_pcpys, pcpys_opn},
  {opc04_pcpysn, pcpysn_opn},
  {opc04_pcpyse, pcpyse_opn},

  {opc04_pcmpeq, pcmpeq_opn},
  {opc04_pcmpne, pcmpne_opn},
  {opc04_pcmplt, pcmplt_opn},
  {opc04_pcmple, pcmple_opn},
  {opc04_pcmpun, pcmpun_opn},

  {opc04_pfmax, pfmax_opn},
  {opc04_pfmin, pfmin_opn},

  {opc04_pcvtsp, pcvtsp_opn},

  {opc04_pextl, pextl_opn},
  {opc04_pexth, pexth_opn},

  {opc04_pcvtfi, pcvtfi_opn},
  {0, 0}
};
#endif

#ifdef NEW_TTL
/*
group_t ttl_group[] = {
    {ttl_mvtvp,           ttl_mvtvp_opn},
    {ttl_mvfvp,           ttl_mvfvp_opn},
    {ttl_setnvm,          ttl_setnvm_opn},
    {ttl_setvm,           ttl_setvm_opn},
    {ttl_vctlz,           ttl_vctlz_opn},
    {ttl_vcttz,           ttl_vcttz_opn},
    {ttl_vctpop,          ttl_vctpop_opn},
    {ttl_vextsl,          ttl_vextsl_opn},
    {ttl_vextsh,          ttl_vextsh_opn},
    {ttl_viota,           ttl_viota_opn},
    {ttl_vskewh,          ttl_vskewh_opn},
    {ttl_vskewl,          ttl_vskewl_opn},
    {ttl_vldt,            ttl_vldt_opn},
    {ttl_vlds,            ttl_vlds_opn},
    {ttl_vldq,            ttl_vldq_opn},
    {ttl_vldl,            ttl_vldl_opn},
    {ttl_vstt,            ttl_vstt_opn},
    {ttl_vsts,            ttl_vsts_opn},
    {ttl_vstq,            ttl_vstq_opn},
    {ttl_vstl,            ttl_vstl_opn},
    {ttl_vgathq,          ttl_vgathq_opn},
    {ttl_vgathl,          ttl_vgathl_opn},
    {ttl_vgatht,          ttl_vgatht_opn},
    {ttl_vgaths,          ttl_vgaths_opn},
    {ttl_vscatq,          ttl_vscatq_opn},
    {ttl_vscatl,          ttl_vscatl_opn},
    {ttl_vscatt,          ttl_vscatt_opn},
    {ttl_vscats,          ttl_vscats_opn},
    {ttl_vvaddt,          ttl_vvaddt_opn},
    {ttl_vvadds,          ttl_vvadds_opn},
    {ttl_vvaddq,          ttl_vvaddq_opn},
    {ttl_vvaddl,          ttl_vvaddl_opn},
    {ttl_vvsubt,          ttl_vvsubt_opn},
    {ttl_vvsubs,          ttl_vvsubs_opn},
    {ttl_vvsubq,          ttl_vvsubq_opn},
    {ttl_vvsubl,          ttl_vvsubl_opn},
    {ttl_vvmult,          ttl_vvmult_opn},
    {ttl_vvmuls,          ttl_vvmuls_opn},
    {ttl_vvmulq,          ttl_vvmulq_opn},
    {ttl_vvmull,          ttl_vvmull_opn},
    {ttl_vvdivt,          ttl_vvdivt_opn},
    {ttl_vvdivs,          ttl_vvdivs_opn},
    {ttl_vsqrtt,          ttl_vsqrtt_opn},
    {ttl_vsqrts,          ttl_vsqrts_opn},
    {ttl_vsaddt,          ttl_vsaddt_opn},
    {ttl_vsadds,          ttl_vsadds_opn},
    {ttl_vssubt,          ttl_vssubt_opn},
    {ttl_vssubs,          ttl_vssubs_opn},
    {ttl_vsmult,          ttl_vsmult_opn},
    {ttl_vsmuls,          ttl_vsmuls_opn},
    {ttl_vsdivt,          ttl_vsdivt_opn},
    {ttl_vsdivs,          ttl_vsdivs_opn},
    {ttl_vsaddq,          ttl_vsaddq_opn},
    {ttl_vsaddl,          ttl_vsaddl_opn},
    {ttl_vssubq,          ttl_vssubq_opn},
    {ttl_vssubl,          ttl_vssubl_opn},
    {ttl_vsmulq,          ttl_vsmulq_opn},
    {ttl_vsmull,          ttl_vsmull_opn},
    {ttl_vsand,           ttl_vsand_opn},
    {ttl_vsbis,           ttl_vsbis_opn},
    {ttl_vsxor,           ttl_vsxor_opn},
    {ttl_vsbic,           ttl_vsbic_opn},
    {ttl_vsornot,         ttl_vsornot_opn},
    {ttl_vseqv,           ttl_vseqv_opn},
    {ttl_vvand,           ttl_vvand_opn},
    {ttl_vvbis,           ttl_vvbis_opn},
    {ttl_vvxor,           ttl_vvxor_opn},
    {ttl_vvbic,           ttl_vvbic_opn},
    {ttl_vvornot,         ttl_vvornot_opn},
    {ttl_vveqv,           ttl_vveqv_opn},
    {ttl_vvcmpeq,         ttl_vvcmpeq_opn},
    {ttl_vvcmple,         ttl_vvcmple_opn},
    {ttl_vvcmplt,         ttl_vvcmplt_opn},
    {ttl_vscmpeq,         ttl_vscmpeq_opn},
    {ttl_vscmple,         ttl_vscmple_opn},
    {ttl_vscmplt,         ttl_vscmplt_opn},
    {ttl_vvcmpule,        ttl_vvcmpule_opn},
    {ttl_vvcmpult,        ttl_vvcmpult_opn},
    {ttl_vscmpule,        ttl_vscmpule_opn},
    {ttl_vscmpult,        ttl_vscmpult_opn},
    {ttl_vvcmpbge,        ttl_vvcmpbge_opn},
    {ttl_vscmpbge,        ttl_vscmpbge_opn},
    {ttl_vcvtqs,          ttl_vcvtqs_opn},
    {ttl_vcvtqt,          ttl_vcvtqt_opn},
    {ttl_vcvtst,          ttl_vcvtst_opn},
    {ttl_vcvttq,          ttl_vcvttq_opn},
    {ttl_vcvtts,          ttl_vcvtts_opn},
    {ttl_vsextbl,         ttl_vsextbl_opn},
    {ttl_vsextwl,         ttl_vsextwl_opn},
    {ttl_vsextll,         ttl_vsextll_opn},
    {ttl_vsextql,         ttl_vsextql_opn},
    {ttl_vsextwh,         ttl_vsextwh_opn},
    {ttl_vsextlh,         ttl_vsextlh_opn},
    {ttl_vsextqh,         ttl_vsextqh_opn},
    {ttl_vvextbl,         ttl_vvextbl_opn},
    {ttl_vvextwl,         ttl_vvextwl_opn},
    {ttl_vvextll,         ttl_vvextll_opn},
    {ttl_vvextql,         ttl_vvextql_opn},
    {ttl_vvextwh,         ttl_vvextwh_opn},
    {ttl_vvextlh,         ttl_vvextlh_opn},
    {ttl_vvextqh,         ttl_vvextqh_opn},
    {ttl_vsinsbl,         ttl_vsinsbl_opn},
    {ttl_vsinswl,         ttl_vsinswl_opn},
    {ttl_vsinsll,         ttl_vsinsll_opn},
    {ttl_vsinsql,         ttl_vsinsql_opn},
    {ttl_vsinswh,         ttl_vsinswh_opn},
    {ttl_vsinslh,         ttl_vsinslh_opn},
    {ttl_vsinsqh,         ttl_vsinsqh_opn},
    {ttl_vvinsbl,         ttl_vvinsbl_opn},
    {ttl_vvinswl,         ttl_vvinswl_opn},
    {ttl_vvinsll,         ttl_vvinsll_opn},
    {ttl_vvinsql,         ttl_vvinsql_opn},
    {ttl_vvinswh,         ttl_vvinswh_opn},
    {ttl_vvinslh,         ttl_vvinslh_opn},
    {ttl_vvinsqh,         ttl_vvinsqh_opn},
    {ttl_vvmerg,          ttl_vvmerg_opn},
    {ttl_vsmerg,          ttl_vsmerg_opn},
    {ttl_vvmskbl,         ttl_vvmskbl_opn},
    {ttl_vvmskwl,         ttl_vvmskwl_opn},
    {ttl_vvmskll,         ttl_vvmskll_opn},
    {ttl_vvmskql,         ttl_vvmskql_opn},
    {ttl_vvmskwh,         ttl_vvmskwh_opn},
    {ttl_vvmsklh,         ttl_vvmsklh_opn},
    {ttl_vvmskqh,         ttl_vvmskqh_opn},
    {ttl_vsmskbl,         ttl_vsmskbl_opn},
    {ttl_vsmskwl,         ttl_vsmskwl_opn},
    {ttl_vsmskll,         ttl_vsmskll_opn},
    {ttl_vsmskql,         ttl_vsmskql_opn},
    {ttl_vsmskwh,         ttl_vsmskwh_opn},
    {ttl_vsmsklh,         ttl_vsmsklh_opn},
    {ttl_vsmskqh,         ttl_vsmskqh_opn},
    {ttl_vssra,           ttl_vssra_opn},
    {ttl_vvsra,           ttl_vvsra_opn},
    {ttl_vssll,           ttl_vssll_opn},
    {ttl_vvsll,           ttl_vvsll_opn},
    {ttl_vssrl,           ttl_vssrl_opn},
    {ttl_vvsrl,           ttl_vvsrl_opn},
    {ttl_vs4addq,         ttl_vs4addq_opn},
    {ttl_vs8addq,         ttl_vs8addq_opn},
    {ttl_vs4addl,         ttl_vs4addl_opn},
    {ttl_vs8addl,         ttl_vs8addl_opn},
    {ttl_vs4subq,         ttl_vs4subq_opn},
    {ttl_vs8subq,         ttl_vs8subq_opn},
    {ttl_vs4subl,         ttl_vs4subl_opn},
    {ttl_vs8subl,         ttl_vs8subl_opn},
    {ttl_vvumulh,         ttl_vvumulh_opn},
    {ttl_vsumulh,         ttl_vsumulh_opn},
    {ttl_vvzap,           ttl_vvzap_opn},
    {ttl_vszap,           ttl_vszap_opn},
    {ttl_vvzapnot,        ttl_vvzapnot_opn},
    {ttl_vszapnot,        ttl_vszapnot_opn},
    {ttl_vvcmpteq,        ttl_vvcmpteq_opn},
    {ttl_vvcmptle,        ttl_vvcmptle_opn},
    {ttl_vvcmptlt,        ttl_vvcmptlt_opn},
    {ttl_vscmpteq,        ttl_vscmpteq_opn},
    {ttl_vscmptle,        ttl_vscmptle_opn},
    {ttl_vscmptlt,        ttl_vscmptlt_opn},
    {0, 0}    
};
*/
#endif

#ifdef NEW_TLDS
group_t tlds_group[] = {
  {tlds_bs,	tlds_bs_opn},
  {tlds_bns,tlds_bns_opn},
  {tlds_q,tlds_q_opn},
  {tlds_arm,tlds_arm_opn},
  {tlds_en,tlds_en_opn},
  {0, 0}
};
#endif

group_t opc14_group[] = {
  {opc14_itofs, itofs_opn},
  {opc14_itoff, itoff_opn},
  {opc14_itoft, itoft_opn},  
  {opc14_sqrtsc, sqrtsc_opn},
  {opc14_sqrttc, sqrttc_opn},
  {opc14_sqrtsm, sqrtsm_opn},
  {opc14_sqrttm, sqrttm_opn},
  {opc14_sqrts, sqrts_opn},
  {opc14_sqrtt, sqrtt_opn},
  {opc14_sqrtsd, sqrtsd_opn},
  {opc14_sqrttd, sqrttd_opn},
  {opc14_sqrtsuc, sqrtsuc_opn},
  {opc14_sqrttuc, sqrttuc_opn},
  {opc14_sqrtsum, sqrtsum_opn},
  {opc14_sqrttum, sqrttum_opn},
  {opc14_sqrtsu, sqrtsu_opn},
  {opc14_sqrttu, sqrttu_opn},
  {opc14_sqrtsud, sqrtsud_opn},
  {opc14_sqrttud, 	sqrttud_opn},
  {opc14_sqrtssuc,       sqrtssuc_opn},
  {opc14_sqrttsuc, 	sqrttsuc_opn},
  {opc14_sqrtssum, 	sqrtssum_opn},
  {opc14_sqrttsum, 	sqrttsum_opn},
  {opc14_sqrtssu, 	sqrtssu_opn},
  {opc14_sqrttsu, 	sqrttsu_opn},
  {opc14_sqrtssud, 	sqrtssud_opn},
  {opc14_sqrttsud, 	sqrttsud_opn},
  {opc14_sqrtssuic, 	sqrtssuic_opn},
  {opc14_sqrttsuic, 	sqrttsuic_opn},
  {opc14_sqrtssuim, 	sqrtssuim_opn},
  {opc14_sqrttsuim, 	sqrttsuim_opn},
  {opc14_sqrtssui, 	sqrtssui_opn},
  {opc14_sqrttsui, 	sqrttsui_opn},
  {opc14_sqrtssuid, 	sqrtssuid_opn},
  {opc14_sqrttsuid, 	sqrttsuid_opn},
  {0, 0}
};

group_t intmisc_group[] = {
  {intmisc_sextb, sextb_opn},
  {intmisc_sextw, sextw_opn},
  {intmisc_perr, perr_opn},
  {intmisc_minub8, minub8_opn},
  {intmisc_minsb8, minsb8_opn},
  {intmisc_minuw4, minuw4_opn},
  {intmisc_minsw4, minsw4_opn},
  {intmisc_maxub8, maxub8_opn},
  {intmisc_maxsb8, maxsb8_opn},
  {intmisc_maxuw4, maxuw4_opn},
  {intmisc_maxsw4, maxsw4_opn},
  {intmisc_pklb, pklb_opn},
  {intmisc_pkwb, pkwb_opn},
  {intmisc_unpkbl, unpkbl_opn},
  {intmisc_unpkbw, unpkbw_opn},
  {intmisc_ctpop, ctpop_opn},
  {intmisc_ctlz, ctlz_opn},
  {intmisc_cttz, cttz_opn},
  {intmisc_ftois, ftois_opn},
  {intmisc_ftoit, ftoit_opn},

#ifdef NEW_MVI
  {intmisc_paddsb8, paddsb8_opn},
  {intmisc_paddsw4, paddsw4_opn},
  {intmisc_paddub8, paddub8_opn},
  {intmisc_padduw4, padduw4_opn},

  {intmisc_psubsb8, psubsb8_opn},
  {intmisc_psubsw4, psubsw4_opn},
  {intmisc_psubub8, psubub8_opn},
  {intmisc_psubuw4, psubuw4_opn},

  {intmisc_pmulluw4, pmulluw4_opn},
  {intmisc_pmulhuw4, pmulhuw4_opn},
  {intmisc_pminmaxsl2, pminmaxsl2_opn},
  {intmisc_pminmaxul2, pminmaxul2_opn},

  {intmisc_pminmaxsb8, pminmaxsb8_opn},
  {intmisc_pminmaxsw4, pminmaxsw4_opn},
  {intmisc_pminmaxub8, pminmaxub8_opn},
  {intmisc_pminmaxuw4, pminmaxuw4_opn},

  {intmisc_taddsb8, taddsb8_opn},
  {intmisc_taddsw4, taddsw4_opn},
  {intmisc_taddub8, taddub8_opn},
  {intmisc_tadduw4, tadduw4_opn},

  {intmisc_tsubsb8, tsubsb8_opn},
  {intmisc_tsubsw4, tsubsw4_opn},
  {intmisc_tsubub8, tsubub8_opn},
  {intmisc_tsubuw4, tsubuw4_opn},

  {intmisc_tmulsb8, tmulsb8_opn},
  {intmisc_tmulsw4, tmulsw4_opn},
  {intmisc_tmulub8, tmulub8_opn},
  {intmisc_tmuluw4, tmuluw4_opn},
  {intmisc_tmulusb8, tmulusb8_opn},
  {intmisc_tmulusw4, tmulusw4_opn},

  {intmisc_psll2, psll2_opn},

  {intmisc_psrb8, psrb8_opn},
  {intmisc_psrw4, psrw4_opn},
  {intmisc_pslb8, pslb8_opn},
  {intmisc_pslw4, pslw4_opn},

  {intmisc_psrl2,  psrl2_opn},
  {intmisc_psral2, psral2_opn},
  {intmisc_psrab8, psrab8_opn},
  {intmisc_psraw4, psraw4_opn},

  {intmisc_pkswb8, pkswb8_opn},
  {intmisc_pkslw4, pkslw4_opn},
  {intmisc_pkuwb8, pkuwb8_opn},
  {intmisc_pkulw4, pkulw4_opn},

  {intmisc_upksbw4, upksbw4_opn},
  {intmisc_upkswl2, upkswl2_opn},
  {intmisc_upkubw4, upkubw4_opn},
  {intmisc_upkuwl2, upkuwl2_opn},

  {intmisc_tabserrsb8, tabserrsb8_opn},
  {intmisc_tabserrub8, tabserrub8_opn},
  {intmisc_tabserrsw4, tabserrsw4_opn},
  {intmisc_tabserruw4, tabserruw4_opn},

  {intmisc_tsqerrsb8, tsqerrsb8_opn},
  {intmisc_tsqerrub8, tsqerrub8_opn},
  {intmisc_tsqerrsw4, tsqerrsw4_opn},
  {intmisc_tsqerruw4, tsqerruw4_opn},

  {intmisc_permb8, permb8_opn},
  {intmisc_gpkblb4, gpkblb4_opn},

  {intmisc_paddsl2, paddsl2_opn},
  {intmisc_paddul2, paddul2_opn},
  {intmisc_psubsl2, psubsl2_opn},
  {intmisc_psubul2, psubul2_opn},
#endif

  {0, 0}
};

group_t defgroup[] = {
  {op_opc01,	res_opc01},
  {op_opc02,	res_opc02},
  {op_opc03,	res_opc03},
  {op_opc04,	res_opc04},
  {op_opc05,	res_opc05},
  {op_opc06,	res_opc06},
  {op_opc07,	res_opc07},
  {op_lda,	lda_opn},
  {op_ldah,	ldah_opn},
  {op_ldbu,	ldb_opn},
  {op_ldq_u,	ldq_u_opn},
  {op_ldwu,	ldw_opn},
  {op_stw,	stw_opn},
  {op_stb,	stb_opn},
  {op_stq_u,	stq_u_opn},
  {op_opc14,	res_opc14},
  {op_pal19,	pal19_opn},
  {op_pal1b,	pal1b_opn},
  {op_pal1d,	pal1d_opn},
  {op_pal1e,	pal1e_opn},
  {op_pal1f,	pal1f_opn},
  {op_ldf,	ldf_opn},
  {op_ldg,	ldg_opn},
  {op_lds,	lds_opn},
  {op_ldt,	ldt_opn},
  {op_stf,	stf_opn},
  {op_stg,	stg_opn},
  {op_sts,	sts_opn},
  {op_stt,	stt_opn},
  {op_ldl,	ldl_opn},
  {op_ldq,	ldq_opn},
  {op_ldl_l,	ldl_l_opn},
  {op_ldq_l,	ldq_l_opn},
  {op_stl,	stl_opn},
  {op_stq,	stq_opn},
  {op_stl_c,	stl_c_opn},
  {op_stq_c,	stq_c_opn},
  {op_br,	br_opn},
  {op_fbeq,	fbeq_opn},
  {op_fblt,	fblt_opn},
  {op_fble,	fble_opn},
  {op_bsr,	bsr_opn},
  {op_fbne,	fbne_opn},
  {op_fbge,	fbge_opn},
  {op_fbgt,	fbgt_opn},
  {op_blbc,	blbc_opn},
  {op_beq,	beq_opn},
  {op_blt,	blt_opn},
  {op_ble,	ble_opn},
  {op_blbs,	blbs_opn},
  {op_bne,	bne_opn},
  {op_bge,	bge_opn},
  {op_bgt,	bgt_opn},
  {0, 0}
};


/* desc_table[]: array of op_desc structs.
 * {char *opname, PFPI *func, int iflags }
 */

struct op_desc desc_table[] = {
#include "desc_table.inc"
};

/* This is to force gcc to include exception information */
int mumble() {
  return 0;
}





